### PR TITLE
Add Python 3 support

### LINKED ISSUE #66: Cannot Import Name 'izip'
By running your example code, I receive the following error.

`Traceback (most recent call last):
  File "C:\Users\Administrator.EvanCasePC\Desktop\test.py", line 1, in <module>
    from simpleai.search import SearchProblem, astar
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\simpleai\search\__init__.py", line 3, in <module>
    from simpleai.search.traditional import breadth_first, depth_first, limited_depth_first, iterative_limited_depth_first, uniform_cost, greedy, astar
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\simpleai\search\traditional.py", line 2, in <module>
    from simpleai.search.utils import FifoList, BoundedPriorityQueue, LifoList
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\simpleai\search\utils.py", line 4, in <module>
    from itertools import izip
ImportError: cannot import name 'izip'`

### PR DESCRIPTION
**Pull request by anassinator**
Fixes #66 and other small syntax issues that prevented this from running on Python 3.x. Of course, Python 2.x should still work.

Tests seem to still pass, but I have only used a subset of this package myself, so I can't guarantee that everything that the tests don't cover work as expected on 3.x.

### CODE REVIEW

**Comment by fisadev** [comment]
Thanks a lot! There is only one detail I would change: I would add the print_function import to the files that do prints, to be sure the print behaves the same in both versions of python. Otherwise, there is some risk that prints might behave different (example: ``print(1, 2)`` would print ``1 2`` in python 3, and ``(1, 2)`` in python 2).

``from __future__ import print_function``

Can you add that? Then I will merge it and do some tests to be sure everything is ok.

Again, thanks a lot, this was a pending task since a long time ago!

**Comment by anassinator** [comment]
Alright! I also realized that I forgot to update the samples, so I'll do all of that and I'll let you know when I'm done.

**Comment by fisadev** [comment]
Ok! And if there is anything you need help with, please ask! :)

**Comment by anassinator** [comment]
So I realized I had made a mistake in running the tests the first time. So far, everything seems to have been ported successfully to Python 3 except for the following 6 test errors/failures:

```
.F..............................E.........................................................................................................FF.F......................F..........................................
======================================================================
ERROR: test_leave_one_out (machine_learning.test_classifiers.BaseTestDtree_Pseudo_CorpusIris)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/machine_learning/test_classifiers.py", line 125, in test_leave_one_out
    self.classifier, len(self.corpus))
  File "/Users/anass/Dev/school/simpleai/simpleai/machine_learning/evaluation.py", line 55, in kfold
    if classifier.classify(data)[0] == problem.target(data):
TypeError: 'NoneType' object is not subscriptable

======================================================================
FAIL: test_equal_classification (machine_learning.test_classifiers.BaseTestDtree_LargeData_CorpusIris)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/machine_learning/test_classifiers.py", line 151, in test_equal_classification
    self.assertEqual(pseudo.classify(test), self.this.classify(test))
AssertionError: Tuples differ: (2, 1.0) != (2, 0.9696969696969697)

First differing element 1:
1.0
0.9696969696969697

- (2, 1.0)
+ (2, 0.9696969696969697)

======================================================================
FAIL: test_chained_revise_calls_remove_non_obvious_problems (search.test_arc_concistency.TestAC3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/search/test_arc_concistency.py", line 101, in test_chained_revise_calls_remove_non_obvious_problems
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_if_variable_has_no_domain_left_returns_false (search.test_arc_concistency.TestAC3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/search/test_arc_concistency.py", line 77, in test_if_variable_has_no_domain_left_returns_false
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_adds_pairs_in_both_directions (search.test_arc_concistency.TestAllArcs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/search/test_arc_concistency.py", line 23, in test_adds_pairs_in_both_directions
    self.assertEqual(arcs_result, arcs_expected)
AssertionError: Items in the second set but not the first:
('A', 'B')
('B', 'A')

======================================================================
FAIL: test_beam (search.test_local.TestLocalSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/search/test_local.py", line 19, in test_beam
    self.assertEqual(result.state, GOAL)
AssertionError: 'i' != 'iabcabc'
- i
+ iabcabc


----------------------------------------------------------------------
Ran 207 tests in 4.583s

FAILED (failures=5, errors=1)
```

Running the same in Python 2 yields no errors for me, so there are some weird edge cases that I'm still unaware of at the moment. Any help would be appreciated!

**Comment by anassinator** [comment]
Ok fixed most of them and got it down to only 1 failure and 1 error:

```
.F..............................E..............................................................................................................................................................................
======================================================================
ERROR: test_leave_one_out (machine_learning.test_classifiers.BaseTestDtree_Pseudo_CorpusIris)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/machine_learning/test_classifiers.py", line 125, in test_leave_one_out
    self.classifier, len(self.corpus))
  File "/Users/anass/Dev/school/simpleai/simpleai/machine_learning/evaluation.py", line 55, in kfold
    if classifier.classify(data)[0] == problem.target(data):
TypeError: 'NoneType' object is not subscriptable

======================================================================
FAIL: test_equal_classification (machine_learning.test_classifiers.BaseTestDtree_LargeData_CorpusIris)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anass/Dev/school/simpleai/tests/machine_learning/test_classifiers.py", line 151, in test_equal_classification
    self.assertEqual(pseudo.classify(test), self.this.classify(test))
AssertionError: Tuples differ: (2, 1.0) != (2, 0.9696969696969697)

First differing element 1:
1.0
0.9696969696969697

- (2, 1.0)
+ (2, 0.9696969696969697)

----------------------------------------------------------------------
Ran 207 tests in 4.699s

FAILED (failures=1, errors=1)
```

**Comment by fisadev** [comment]
I'm having some complicated days, work, grading student practices and fixing plumbing issues at home, so I wasn't able to look at it. But I'm pretty sure tomorrow I'll have some free time to try to identify the source of that failing test :)

**Comment by anassinator** [comment]
@fisadev Any luck?

**Comment by fisadev** [comment]
@anassinator spent some time on it, it's difficult to pinpoint the source of the difference, but I wasn't able to give it too much time. I'll try again this weekend, which has an extra day (holiday here) :)

**Comment by fisadev** [comment]
Ok, I finally found the issue in the failing one: the ``round()`` changes between python 2 and 3. The tests use the iris dataset (from the file ``iris.txt``). The values are rounded up, using the ``round()`` builtin. But...

Python 2: 

    round(0.5)
    >>> 1.0

Python 3:

    round(0.5)
    >>> 0

A quick fix would be to use a custom round function, which is ugly. Tomorrow I'll try to find a better solution, and continue with the other problematic test. Sorry for the delays, this is hard and I'm short on free time, hehe.

**Comment by anassinator** [comment]
Oh nice! I'm gonna have more time later next week to take another look and help out then.

**Comment by fisadev** [comment]
We did a sprint on these bugs during PyConAr 2016. It turns out that ``round()`` itself wasn't the issue, the issue was a bug in the decission trees algorithm, which by pure luck didn't occur with the old ``round()`` behavior, but it manifested itself with the new one. @diegomvh found the issue and fixed it. After the fix, we have only one remaining failing test, which I'm working today to solve :)

**Comment by fisadev** [comment]
Done! Merged and released (version 0.8). SimpleAI now officially runs on Python 3.

@anassinator Thanks a lot for your work on this issue, it was something we needed since long ago :)

Also, thanks to @diegomvh for his work on the failing test and @machinalis for the time they gave me to work on the final details.

**Comment by anassinator** [comment]
Perfect! Thank you! Sorry I was too busy to work on this the past couple of weeks.

**Pull request merged**
